In [26]:
import pandas as pd
import matplotlib.pyplot as plt

In [27]:
counts = pd.read_csv("raw/pedestrian-counting-system-monthly-counts-per-hour.csv")
locations = pd.read_csv("raw/pedestrian-counting-system-sensor-locations.csv")

In [28]:
counts.head(5)

,ID,Location_ID,Sensing_Date,HourDay,Direction_1,Direction_2,Total_of_Directions,Sensor_Name,Location
0,47220260804,47,2026-08-04,2,6,18,24,Eli250_T,"-37.81258467, 144.9625775"
1,36320260804,36,2026-08-04,3,6,1,7,Que85_T,"-37.81652527, 144.96121062"
2,162020260804,162,2026-08-04,0,43,30,73,Eli489_T,"-37.80740397, 144.95987909"
3,29320260804,29,2026-08-04,3,0,2,2,AG_T,"-37.8199817, 144.96872865"
4,84020260804,84,2026-08-04,0,42,28,70,ElFi_T,"-37.81798049, 144.96503383"

In [30]:
counts["Location_ID"].nunique()

103

In [29]:
locations.head(5)

,Location_ID,Sensor_Description,Sensor_Name,Installation_Date,Note,Location_Type,Status,Direction_1,Direction_2,Latitude,Longitude,Location
0,3,Melbourne Central,Swa295_T,2009-03-25,NaN,Outdoor,A,North,South,-37.811015,144.964295,"-37.81101524, 144.96429485"
1,5,Princes Bridge,PriNW_T,2009-03-26,Replace with: 00:6e:02:01:9e:54,Outdoor,A,North,South,-37.818742,144.967877,"-37.81874249, 144.96787656"
2,9,Southern Cross Station,Col700_T,2009-03-23,NaN,Outdoor,A,East,West,-37.819830,144.951026,"-37.81982992, 144.95102555"
3,11,Docklands Waterfront City Building Side,WatCit_T,2009-01-20,Device has been replaced with new sensor on 22...,Outdoor,A,East,West,-37.815667,144.939744,"-37.81566651, 144.93974366"
4,12,New Quay,NewQ_T,2009-01-21,NaN,Outdoor,A,East,West,-37.814580,144.942924,"-37.81457988, 144.94292398"

In [24]:
len(locations)

134

In [31]:
locations["Location_ID"].nunique()

134